# Use the tensorflow gpu release
#FROM tensorflow/tensorflow:latest-gpu

#Take Ubuntu 18.04 as basis
FROM ubuntu:18.04 as builder
# Install GPU drivers and TensorRT
# Add NVIDIA package repositories
RUN apt update
RUN apt install -y wget gnupg gnupg2 gnupg1 software-properties-common
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
RUN mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
RUN add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
RUN apt update

RUN wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb

RUN apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
RUN apt update

RUN wget https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/libnvinfer7_7.1.3-1+cuda11.0_amd64.deb
RUN apt install -y ./libnvinfer7_7.1.3-1+cuda11.0_amd64.deb
RUN apt update

# Install development and runtime libraries (~4GB)
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --allow-downgrades \
    cuda-11-0 \
    libcudnn8=8.0.4.30-1+cuda11.0  \
    libcudnn8-dev=8.0.4.30-1+cuda11.0

# Reboot. Check that GPUs are visible using the command: nvidia-smi
# Install TensorRT. Requires that libcudnn8 is installed above.
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libnvinfer7=7.1.3-1+cuda11.0 \
    libnvinfer-dev=7.1.3-1+cuda11.0 \
    libnvinfer-plugin7=7.1.3-1+cuda11.0

# Add depencies and needed python libraries
FROM builder AS AddDepenencies

RUN DEBIAN_FRONTEND=noninteractive apt install -y git curl unzip python3 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-opencv
COPY ./requirements.txt .
#RUN pip3 install requirements.txt
#RUN pip3 install matplotlib imageio

# Finally, set up the training environment

WORKDIR /models

COPY /src/. .